WIP - move to homebrew

diff --git a/moodle-docker b/moodle-docker
--- a/moodle-docker
+++ b/moodle-docker
@@ -64,16 +64,18 @@
 # moodle-docker behat 41 addtional
 
 # VARS.
-PLUGIN_VERSION="0.0.9"
+PLUGIN_VERSION="0.0.11"
 MOODLE_LIST=$(cat ${HOMEBREW_PREFIX}/opt/moodle-docker/moodle_versions.txt)
 VERSIONS=$(echo "$MOODLE_LIST" | awk -F'|' '{ print $1 }')
 ARG2_SELECTED_VERSION=""
 VERSION_FOUND=0
 ARG1_ACTION="$1"
 ARG2_SELECTED_VERSION="$2"
+HOMEBREW_OPT_BIN="${HOMEBREW_PREFIX}/opt/moodle-docker/bin"
+
 # ----------------------------------------------------------------
 
-source "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/scripts/helper.sh"
+source "$HOMEBREW_OPT_BIN/scripts/helper.sh"
 log "${GREEN}Moodle docker brew v$PLUGIN_VERSION by Ldesign Media"
 log "${YELLOW}You can read the full documentation here: https://github.com/LdesignMedia/moodle-docker-brew"
 
@@ -144,7 +146,7 @@ export MOODLE_DOCKER_DB=mariadb
 export MOODLE_DOCKER_DB_PORT="330${ARG2_SELECTED_VERSION}"
 export MOODLE_DOCKER_SELENIUM_VNC_PORT="590${ARG2_SELECTED_VERSION}"
 export MOODLE_DOCKER_WEB_PORT="80${ARG2_SELECTED_VERSION}"
-export MOODLE_DOCKER_WWWROOT="${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/${ARG2_SELECTED_VERSION}"
+export MOODLE_DOCKER_WWWROOT="$HOMEBREW_OPT_BIN/moodle/${ARG2_SELECTED_VERSION}"
 
 # Set PHP for older versions
 if [ "$ARG2_SELECTED_VERSION" == "39" ]; then
@@ -167,7 +169,7 @@ log "${YELLOW}When running Available on: http://localhost:$MOODLE_DOCKER_WEB_POR
 if [ "$ARG1_ACTION" == "start" ]; then
 
   # Download the zip file to the moodle directory and name it using the selected_version
-  zip_file="${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/${ARG2_SELECTED_VERSION}.zip"
+  zip_file="$HOMEBREW_OPT_BIN/moodle/${ARG2_SELECTED_VERSION}.zip"
 
   if [ ! -f "$zip_file" ]; then
 
@@ -189,10 +191,10 @@ if [ "$ARG1_ACTION" == "start" ]; then
     abort "Failed to download  $download_url"
   fi
 
-  if [ ! -d "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/${ARG2_SELECTED_VERSION}" ]; then
-    rm -rf "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/moodle"
-    unzip -q "$zip_file" -d "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/"
-    mv "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/moodle" "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/${ARG2_SELECTED_VERSION}"
+  if [ ! -d "$HOMEBREW_OPT_BIN/moodle/${ARG2_SELECTED_VERSION}" ]; then
+    rm -rf "$HOMEBREW_OPT_BIN/moodle/moodle"
+    unzip -q "$zip_file" -d "$HOMEBREW_OPT_BIN/moodle/"
+    mv "$HOMEBREW_OPT_BIN/moodle/moodle" "$HOMEBREW_OPT_BIN/moodle/${ARG2_SELECTED_VERSION}"
 
     log "${GREEN}Moodle directory available at ${PWD}/moodle/${ARG2_SELECTED_VERSION}"
   else
@@ -248,7 +250,7 @@ elif [ "$ARG1_ACTION" == "destroy" ]; then
   if confirm "Do you want to proceed?"; then
 
     # Shut down and destroy containers
-    cd "moodlehq-docker" || abort "moodlehq-docker is missing"
+    cd "$HOMEBREW_OPT_BIN/moodlehq-docker" || abort "moodlehq-docker is missing"
 
     bin/moodle-docker-compose down
 
@@ -262,7 +264,7 @@ elif [ "$ARG1_ACTION" == "destroy" ]; then
 elif [ "$ARG1_ACTION" == "stop" ]; then
 
   log "${GREEN}stopping docker containers."
-  cd "moodlehq-docker" || abort "moodlehq-docker is missing"
+  cd "$HOMEBREW_OPT_BIN/moodlehq-docker" || abort "moodlehq-docker is missing"
   check_is_running
 
   # Shut down and destroy containers
@@ -273,7 +275,7 @@ elif [ "$ARG1_ACTION" == "stop" ]; then
 elif [ "$ARG1_ACTION" == "behat" ]; then
   log "${GREEN}bin/moodle-docker-compose exec -u www-data webserver php admin/tool/behat/cli/run.php $ALL_REMAINING_ARGS"
 
-  cd "moodlehq-docker" || abort "moodlehq-docker is missing"
+  cd "$HOMEBREW_OPT_BIN/moodlehq-docker" || abort "moodlehq-docker is missing"
   check_is_running
 
   bin/moodle-docker-compose exec -u www-data webserver php admin/tool/behat/cli/run.php "$ALL_REMAINING_ARGS"
@@ -283,7 +285,7 @@ elif [ "$ARG1_ACTION" == "behat" ]; then
 elif [ "$ARG1_ACTION" == "phpunit" ]; then
   log "${GREEN}bin/moodle-docker-compose exec webserver vendor/bin/phpunit $ALL_REMAINING_ARGS"
 
-  cd "moodlehq-docker" || abort "moodlehq-docker is missing"
+  cd "$HOMEBREW_OPT_BIN/moodlehq-docker" || abort "moodlehq-docker is missing"
   check_is_running
 
   bin/moodle-docker-compose exec webserver vendor/bin/phpunit "$ALL_REMAINING_ARGS"
@@ -293,7 +295,7 @@ elif [ "$ARG1_ACTION" == "phpunit" ]; then
 elif [ "$ARG1_ACTION" == "update" ]; then
 
   log "${GREEN}Updating container"
-  cd "moodlehq-docker" || abort "moodlehq-docker is missing"
+  cd "$HOMEBREW_OPT_BIN/moodlehq-docker" || abort "moodlehq-docker is missing"
   check_is_running
 
 else
