WIP - move to homebrew

diff --git a/moodle-docker b/moodle-docker
--- a/moodle-docker
+++ b/moodle-docker
@@ -64,7 +64,7 @@
 # moodle-docker behat 41 addtional
 
 # VARS.
-PLUGIN_VERSION="0.0.5"
+PLUGIN_VERSION="0.0.9"
 MOODLE_LIST=$(cat ${HOMEBREW_PREFIX}/opt/moodle-docker/moodle_versions.txt)
 VERSIONS=$(echo "$MOODLE_LIST" | awk -F'|' '{ print $1 }')
 ARG2_SELECTED_VERSION=""
@@ -189,10 +189,10 @@ if [ "$ARG1_ACTION" == "start" ]; then
     abort "Failed to download  $download_url"
   fi
 
-  if [ ! -d "${HOMEBREW_PREFIX}/opt/bin/moodle/${ARG2_SELECTED_VERSION}" ]; then
-    rm -rf "${HOMEBREW_PREFIX}/opt/bin/moodle/moodle"
-    unzip -q "$zip_file" -d "${HOMEBREW_PREFIX}/opt/bin/moodle/"
-    mv "${HOMEBREW_PREFIX}/opt/bin/moodle/moodle" "${HOMEBREW_PREFIX}/opt/bin/moodle/${ARG2_SELECTED_VERSION}"
+  if [ ! -d "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/${ARG2_SELECTED_VERSION}" ]; then
+    rm -rf "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/moodle"
+    unzip -q "$zip_file" -d "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/"
+    mv "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/moodle" "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodle/${ARG2_SELECTED_VERSION}"
 
     log "${GREEN}Moodle directory available at ${PWD}/moodle/${ARG2_SELECTED_VERSION}"
   else
@@ -201,8 +201,8 @@ if [ "$ARG1_ACTION" == "start" ]; then
 
   log "$COMPOSE_PROJECT_NAME"
 
-  cp "${HOMEBREW_PREFIX}/opt/bin/moodlehq-docker/config.docker-template.php" "$MOODLE_DOCKER_WWWROOT/config.php"
-  cd "${HOMEBREW_PREFIX}/opt/bin/moodlehq-docker" || abort "moodlehq-docker is missing"
+  cp "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodlehq-docker/config.docker-template.php" "$MOODLE_DOCKER_WWWROOT/config.php"
+  cd "${HOMEBREW_PREFIX}/opt/moodle-docker/bin/moodlehq-docker" || abort "moodlehq-docker is missing"
 
   # Make sure Moodle is installed.
   if [ ! -f "$MOODLE_DOCKER_WWWROOT/version.php" ]; then
